// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1e6HulQVaJs1sJFkoBGISqwRgwOx08fE',
    appId: '1:850742267226:web:ea22790c7c29ee2516b763',
    messagingSenderId: '850742267226',
    projectId: 'she-5e596',
    authDomain: 'she-5e596.firebaseapp.com',
    storageBucket: 'she-5e596.appspot.com',
    measurementId: 'G-NNGXGKJM7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK8jZCYRqFipX2TLE0G-VDMSQsPzdW9fA',
    appId: '1:850742267226:android:644288338d19019316b763',
    messagingSenderId: '850742267226',
    projectId: 'she-5e596',
    storageBucket: 'she-5e596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnhrJSUQ2gqFR_WWMzAur2oRy5_kCk68',
    appId: '1:850742267226:ios:9fc1ce982dcb58fa16b763',
    messagingSenderId: '850742267226',
    projectId: 'she-5e596',
    storageBucket: 'she-5e596.appspot.com',
    iosBundleId: 'com.example.securesheapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnhrJSUQ2gqFR_WWMzAur2oRy5_kCk68',
    appId: '1:850742267226:ios:9fc1ce982dcb58fa16b763',
    messagingSenderId: '850742267226',
    projectId: 'she-5e596',
    storageBucket: 'she-5e596.appspot.com',
    iosBundleId: 'com.example.securesheapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1e6HulQVaJs1sJFkoBGISqwRgwOx08fE',
    appId: '1:850742267226:web:c5dfd1203320b3e516b763',
    messagingSenderId: '850742267226',
    projectId: 'she-5e596',
    authDomain: 'she-5e596.firebaseapp.com',
    storageBucket: 'she-5e596.appspot.com',
    measurementId: 'G-X4F894C6JF',
  );
}
